import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// Served locally through Laravel Valet at https://expense-tracker.test, which
// proxies TLS traffic to this dev server. The dev server in turn proxies /api
// to the Go backend, so the SPA stays same-origin with the API and the HttpOnly
// refresh cookie works without CORS friction.
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      // Ship a fresh service worker on every deploy without a manual "update" prompt.
      registerType: 'autoUpdate',
      // Icons live in public/ and are generated by `npm run generate-pwa-assets`.
      includeAssets: ['favicon.svg', 'apple-touch-icon-180x180.png'],
      manifest: {
        name: 'Expense Tracker',
        short_name: 'Expenses',
        description: 'Track expenses, categorise spending, and view your dashboard.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        theme_color: '#863bff',
        background_color: '#ffffff',
        icons: [
          {
            src: 'pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Precache the built app shell so it loads instantly and works offline.
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        // SPA client-side routing: serve index.html for navigations...
        navigateFallback: '/index.html',
        // ...but never intercept the Go API — those must always hit the network.
        navigateFallbackDenylist: [/^\/api/],
      },
    }),
  ],
  server: {
    host: '127.0.0.1',
    port: 5173,
    // Accept the Valet host header (Vite blocks unknown hosts by default).
    allowedHosts: ['expense-tracker.test', 'localhost', '127.0.0.1'],
    // Run HMR over Valet's TLS (wss on 443) so hot reload works on the domain.
    hmr: {
      host: 'expense-tracker.test',
      protocol: 'wss',
      clientPort: 443,
    },
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
      },
    },
  },
})
